### ISSUE TITLE
Basic Widget Layout

### ISSUE THREAD

**Issue by valkum** [valkum/orbtk-chat#1]
I imported the file into figma and added some frames for widgets I think are a good start.

https://www.figma.com/file/6VMJui9K204k5GEtMrolkE/Chat-Desktop-App-macOS?node-id=0%3A1

Next step is change the current widget layout to the figma one.

**Comment by ghost** [comment]
I've got an

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/6715107/76109237-5747f980-5fdc-11ea-8e6e-63f67701b5ce.png">

**Comment by valkum** [comment]
ah try again, I changed the permissions of the file

**Comment by valkum** [comment]
I started work on this in this PR #2 
Encountered problems with auto sizing the two columns LeftPane and RightPane.
RightPane has a Container inside with 200x200 but the grid is not sized accordingly

**Comment by ghost** [comment]
I have now access, thank you.

I think there is a bug in the calculation of the `auto` columns and rows. I will check it this week, after I finished my current PR on OrbTk.

**Comment by valkum** [comment]
I identified my problem in `accumulate_desired_size` in `StackLayout`
The height/width depending on the orientation that is not growing is set to the height/width of the last processed child. Using the maximum works, but i am not sure if that is the behaviour we want.

```rust
fn accumulate_desired_size(
    desired_size: &mut (f64, f64),
    desired: DirtySize,
    margin: Thickness,
    orientation: Orientation,
) {
    let width = desired.width() + margin.left() + margin.right();
    let height = desired.height() + margin.top() + margin.bottom();

    match orientation {
        Orientation::Horizontal => {
            desired_size.0 += width;
            desired_size.1 = desired_size.1.max(height);
        }
        Orientation::Vertical => {
            desired_size.0 = desired_size.0.max(width);
            desired_size.1 += height;
        }
    }
}
```
